-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

local v0 = require(script.DanceMain);
return {
    setDances = function(v1) --[[ Line: 7 ]] --[[ Name: setDances ]]
        -- upvalues: v0 (copy)
        v0.setDances(v1);
    end, 
    setFavoriteDances = function(v2) --[[ Line: 11 ]] --[[ Name: setFavoriteDances ]]
        -- upvalues: v0 (copy)
        v0.setFavoriteDances(v2);
    end,
    toggleMenu = function()
        -- upvalues: v0 (copy)
        return v0.toggleMenu();
    end
};
