return {
	{
		name     = "Emoji 1",
		image    = "rbxassetid://115641840435678",
		sound    = "rbxassetid://134576259105128",
		duration = 4,
	},
	{
		name     = "Emoji 2",
		image    = "rbxassetid://104785568532178",
		sound    = "rbxassetid://90087825083279",
		duration = 4,
	},
	{
		name     = "Emoji 3",
		image    = "rbxassetid://89699071310163",
		sound    = "rbxassetid://90087825083279",
		duration = 4,
	},
	{
		name     = "Emoji 4",
		image    = "rbxassetid://77356402010452",
		sound    = "rbxassetid://90087825083279",
		duration = 4,
	},
	{
		name     = "Emoji 5",
		image    = "rbxassetid://94813471134633",
		sound    = "rbxassetid://90087825083279",
		duration = 4,
	},
	{
		name     = "Emoji 6",
		image    = "rbxassetid://98623810471582",
		sound    = "rbxassetid://90087825083279",
		duration = 4,
	},
	{
		name     = "Emoji 7",
		image    = "rbxassetid://87748451090609",
		sound    = "rbxassetid://90087825083279",
		duration = 4,
	},
	{
		name     = "Emoji 8",
		image    = "rbxassetid://84138325760218",
		sound    = "rbxassetid://90087825083279",
		duration = 4,
	},

	hoverSound = "rbxassetid://111213083887701",
	clickSound = "rbxassetid://133445631981492",
}
